import core from "@howells/lint/oxlint/core";

export default {
  extends: [core],
  overrides: [
    {
      // Gauge runs its tests on the node:test runner (tsx --test), not
      // vitest. The shared preset scopes vitest globals and rules to test
      // files, where they collide with the node:test import and assume a
      // runner this repository does not use. node:test tracks every
      // test() promise itself, so the call is intentionally floating.
      files: ["test/**/*.{test,spec}.{ts,tsx}"],
      plugins: ["vitest"],
      rules: {
        "no-redeclare": "off",
        "typescript/no-floating-promises": "off",
        "vitest/consistent-each-for": "off",
        "vitest/consistent-test-filename": "off",
        "vitest/consistent-vitest-vi": "off",
        "vitest/expect-expect": "off",
        "vitest/hoisted-apis-on-top": "off",
        "vitest/max-expects": "off",
        "vitest/max-nested-describe": "off",
        "vitest/no-alias-methods": "off",
        "vitest/no-commented-out-tests": "off",
        "vitest/no-conditional-expect": "off",
        "vitest/no-conditional-tests": "off",
        "vitest/no-disabled-tests": "off",
        "vitest/no-duplicate-hooks": "off",
        "vitest/no-focused-tests": "off",
        "vitest/no-identical-title": "off",
        "vitest/no-import-node-test": "off",
        "vitest/no-interpolation-in-snapshots": "off",
        "vitest/no-large-snapshots": "off",
        "vitest/no-mocks-import": "off",
        "vitest/no-restricted-matchers": "off",
        "vitest/no-restricted-vi-methods": "off",
        "vitest/no-standalone-expect": "off",
        "vitest/no-test-prefixes": "off",
        "vitest/no-test-return-statement": "off",
        "vitest/no-unneeded-async-expect-function": "off",
        "vitest/padding-around-after-all-blocks": "off",
        "vitest/padding-around-test-blocks": "off",
        "vitest/prefer-called-exactly-once-with": "off",
        "vitest/prefer-called-once": "off",
        "vitest/prefer-called-with": "off",
        "vitest/prefer-comparison-matcher": "off",
        "vitest/prefer-describe-function-title": "off",
        "vitest/prefer-each": "off",
        "vitest/prefer-equality-matcher": "off",
        "vitest/prefer-expect-resolves": "off",
        "vitest/prefer-expect-type-of": "off",
        "vitest/prefer-hooks-in-order": "off",
        "vitest/prefer-hooks-on-top": "off",
        "vitest/prefer-import-in-mock": "off",
        "vitest/prefer-importing-vitest-globals": "off",
        "vitest/prefer-lowercase-title": "off",
        "vitest/prefer-mock-promise-shorthand": "off",
        "vitest/prefer-spy-on": "off",
        "vitest/prefer-to-be-falsy": "off",
        "vitest/prefer-to-be-object": "off",
        "vitest/prefer-to-be-truthy": "off",
        "vitest/prefer-to-contain": "off",
        "vitest/prefer-to-have-length": "off",
        "vitest/prefer-todo": "off",
        "vitest/require-hook": "off",
        "vitest/require-local-test-context-for-concurrent-snapshots": "off",
        "vitest/valid-expect": "off",
      },
    },
  ],
};
